import {
	AppSettingsControlNode,
	type AppSettingsData,
	AppSettingsFixedContentInitialPosition,
	AppSettingsGroup,
	AppSettingsLanguage,
	AppSettingsTheme,
	CloudSaveUrlFormat,
	CloudSaveUrlType,
	ColorPickerShowMode,
	DoubleClickAction,
	ExtraToolList,
	GifFormat,
	HdrColorAlgorithm,
	HistoryValidDuration,
	KeyDisplayDirection,
	OcrDetectAfterAction,
	OcrModel,
	TrayIconClickAction,
	TrayIconDefaultIcon,
	VideoMaxSize,
} from "@/types/appSettings";
import { DrawState } from "@/types/draw";
import { ImageFormat } from "@/types/utils/file";
import { getPlatformValue } from "@/utils/platform";
import { defaultAppFunctionConfigs } from "./appFunction";
import { defaultCommonKeyEventSettings } from "./commonKeyEvent";
import { FOCUS_WINDOW_APP_NAME_ENV_VARIABLE } from "./components/chat";
import { defaultDrawToolbarKeyEventSettings } from "./drawToolbarKeyEvent";

export const defaultAppSettingsData: AppSettingsData = {
	[AppSettingsGroup.Common]: {
		theme: AppSettingsTheme.System,
		mainColor: "#1677FF",
		borderRadius: 6,
		enableCompactLayout: false,
		language: AppSettingsLanguage.ZHHans,
		browserLanguage: "",
	},
	[AppSettingsGroup.ThemeSkin]: {
		skinPath: "",
		skinOpacity: 72,
		skinPosition: "center",
		skinBlur: 0,
		skinImageSize: "cover",
		skinMixBlendMode: "unset",
		customCss: "",
		skinMaskBlur: 3,
		skinMaskOpacity: 100,
	},
	[AppSettingsGroup.Screenshot]: {
		uiScale: 100,
		toolbarUiScale: 100,
		controlNode: AppSettingsControlNode.Circle,
		// 在 Mac 上禁用动画
		disableAnimation: getPlatformValue(false, true),
		colorPickerShowMode: ColorPickerShowMode.BeyondSelectRect,
		beyondSelectRectElementOpacity: 100,
		selectRectMaskColor: "#00000080",
		fullScreenAuxiliaryLineColor: "#00000000",
		monitorCenterAuxiliaryLineColor: "#00000000",
		hotKeyTipOpacity: 100,
		colorPickerCenterAuxiliaryLineColor: "#00000000",
		toolbarHiddenToolList: [],
	},
	[AppSettingsGroup.FixedContent]: {
		borderColor: "#dbdbdb",
	},
	[AppSettingsGroup.CommonTrayIcon]: {
		iconPath: "",
		iconPathDark: "",
		defaultIcons: TrayIconDefaultIcon.Default,
		defaultIconsDark: TrayIconDefaultIcon.Default,
		enableTrayIcon: true,
	},
	[AppSettingsGroup.FunctionDraw]: {
		lockDrawTool: true,
		enableSliderChangeWidth: false,
		toolIndependentStyle: true,
		disableQuickSelectElementToolList: [],
	},
	[AppSettingsGroup.Cache]: {
		menuCollapsed: false,
		colorPickerColorFormatIndex: 0,
		prevImageFormat: ImageFormat.PNG,
		prevSelectRect: {
			min_x: 0,
			min_y: 0,
			max_x: 0,
			max_y: 0,
		},
		enableMicrophone: false,
		enableLockDrawTool: false,
		disableArrowPicker: true,
		selectRectRadius: 0,
		selectRectShadowWidth: 0,
		selectRectShadowColor: "#595959",
		lastRectTool: DrawState.Rect,
		lastArrowTool: DrawState.Arrow,
		lastFilterTool: DrawState.Blur,
		lastExtraTool: ExtraToolList.None,
		lastDrawExtraTool: DrawState.Idle,
		lastWatermarkText: "",
		delayScreenshotSeconds: 0,
		lockDragAspectRatio: 0,
		enableTabFindChildrenElements: true,
	},
	[AppSettingsGroup.DrawToolbarKeyEvent]: defaultDrawToolbarKeyEventSettings,
	[AppSettingsGroup.CommonKeyEvent]: defaultCommonKeyEventSettings,
	[AppSettingsGroup.AppFunction]: defaultAppFunctionConfigs,
	[AppSettingsGroup.Render]: {
		antialias: true,
	},
	[AppSettingsGroup.SystemCommon]: {
		autoStart: true,
		runLog: false,
	},
	[AppSettingsGroup.SystemNetwork]: {
		enableProxy: false,
	},
	[AppSettingsGroup.FunctionTranslation]: {
		optimizeAiTranslationLayout: true,
		sourceLanguage: "auto",
		targetLanguage: "zh-CHS",
		// 腾讯 → 金山翻译 → 微软 → Yandex；国内可直连的优先
		translateEngineOrder: ["Transmart", "ICibaTranslate", "Microsoft", "Yandex"],
	},
	[AppSettingsGroup.FunctionTranslationCache]: {
		cacheSourceLanguage: "auto",
		cacheTargetLanguage: "zh-CHS",
	},
	[AppSettingsGroup.FunctionOcr]: {
		ocrModel: OcrModel.RapidOcrV5Server,
	},
	[AppSettingsGroup.FunctionScreenshot]: {
		findChildrenElements: true,
		shortcutCanleTip: false,
		autoSaveOnCopy: false,
		doubleClickAction: DoubleClickAction.Copy,
		copyImageFileToClipboard: false,
		focusedWindowCopyToClipboard: true,
		fullScreenCopyToClipboard: true,
		fastSave: false,
		/** 保存到云端 */
		saveToCloud: false,
		/** 云端保存协议 */
		cloudSaveUrlType: CloudSaveUrlType.S3,
		cloudSaveUrlFormat: CloudSaveUrlFormat.Origin,
		cloudProxyUrl: "",
		s3AccessKeyId: "",
		s3SecretAccessKey: "",
		s3Region: "",
		s3Endpoint: "",
		s3BucketName: "",
		s3PathPrefix: "",
		s3ForcePathStyle: false,
		saveFileDirectory: "",
		saveFileFormat: ImageFormat.PNG,
		ocrAfterAction: OcrDetectAfterAction.None,
		ocrCopyText: true,
		selectRectPresetList: [],
	},
	[AppSettingsGroup.SystemScrollScreenshot]: {
		tryRollback: true,
		imageFeatureThreshold: 24,
		minSide: 128,
		maxSide: 128,
		sampleRate: 1,
		imageFeatureDescriptionLength: 28,
	},
	[AppSettingsGroup.FunctionFixedContent]: {
		zoomWithMouse: true,
		autoResizeWindow: true,
		autoOcr: true,
		autoCopyToClipboard: false,
		initialPosition: AppSettingsFixedContentInitialPosition.MousePosition,
	},
	[AppSettingsGroup.FunctionOutput]: {
		manualSaveFileNameFormat: `SnowShot_{{YYYY-MM-DD_HH-mm-ss}}`,
		autoSaveFileNameFormat: `SnowShot_{{YYYY-MM-DD_HH-mm-ss}}`,
		fastSaveFileNameFormat: `SnowShot_{{YYYY-MM-DD_HH-mm-ss}}`,
		focusedWindowFileNameFormat: `${FOCUS_WINDOW_APP_NAME_ENV_VARIABLE}/SnowShot_{{YYYY-MM-DD_HH-mm-ss}}`,
		fullScreenFileNameFormat: `SnowShot_{{YYYY-MM-DD_HH-mm-ss}}`,
		videoRecordFileNameFormat: `SnowShot_Video_{{YYYY-MM-DD_HH-mm-ss}}`,
		uploadToCloudSaveUrlFormat: `SnowShot_{{YYYY-MM-DD_HH-mm-ss}}`,
	},
	[AppSettingsGroup.FunctionFullScreenDraw]: {
		defaultTool: DrawState.Select,
	},
	[AppSettingsGroup.FunctionVideoRecord]: {
		enableExcludeFromCapture: true,
		saveDirectory: "",
		frameRate: 24,
		gifFrameRate: 10,
		microphoneDeviceName: "",
		hwaccel: true,
		encoder: "libx264",
		encoderPreset: "ultrafast",
		videoMaxSize: VideoMaxSize.P1080,
		gifMaxSize: VideoMaxSize.P1080,
		gifFormat: GifFormat.Gif,
		keyDisplayFontSize: 16,
		keyDisplayBackgroundColor: "rgba(0, 0, 0, 0.42)",
		keyDisplayTextColor: "#ffffff",
		keyDisplayDuration: 3000,
		keyDisplayMergeDuration: 256,
		keyDisplayDirection: KeyDisplayDirection.Vertical,
	},
	[AppSettingsGroup.SystemScreenshot]: {
		ocrHotStart: true,
		ocrModelWriteToMemory: false,
		ocrDetectAngle: false,
		historyValidDuration: HistoryValidDuration.Week,
		recordCaptureHistory: true,
		historySaveEditResult: true,
		/** 尝试使用 Bitmap 格式写入到剪贴板 */
		tryWriteBitmapImageToClipboard: true,
		/** 启用多显示器截图 */
		enableMultipleMonitor: true,
		/** 更正颜色滤镜 */
		correctColorFilter: true,
		/** 更正 HDR 颜色  */
		correctHdrColor: true,
		/** HDR 颜色转换算法 */
		correctHdrColorAlgorithm: HdrColorAlgorithm.Linear,
	},
	[AppSettingsGroup.FunctionTrayIcon]: {
		iconClickAction: TrayIconClickAction.Screenshot,
	},
	[AppSettingsGroup.SystemCore]: {
		/// 热加载页面数量
		hotLoadPageCount: 2,
	},
	[AppSettingsGroup.FunctionGlobalShortcut]: {
		disableOnFocusedFullScreenWindow: false,
	},
};
